# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finger',
            name='browser',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finger',
            name='os',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finger',
            name='fingerprint',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
