# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170425_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finger',
            old_name='fingerprint',
            new_name='finger',
        ),
    ]
